### ISSUE TITLE
StreamHub Github project

### ISSUE THREAD

**Issue by Goldinium** [Goldinium/StreamHub#21]
Hello

This is Microverse JS capstone project
There are two students/contributors

@Pi1998 
@Goldinium 

And this is the Github project link
[https://github.com/Goldinium/StreamHub/projects/1](https://github.com/Goldinium/StreamHub/projects/1)

**Comment by Olamarx** [comment]
Hi @Goldinium,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
- Good use of Kanban board ✔️
- All cards total 15 ✔️
- Fair distribution ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I can see the group tasks were not assigned, I will encourage you to assign it even if both of you would be working on it, assign it to both of you because an unassigned task is more or less not anyone's task.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mckent05** [comment]
Hi @Goldinium, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... It's time to start your capstone :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All tasks have been fairly assigned ✔️ ✔️ 
- Your Kanban board has been well set up 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
